# Generated by Django 3.1.4 on 2020-12-31 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ('-publish',)},
        ),
    ]
